# Generated by Django 4.1.1 on 2022-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedetail',
            name='accNo_img',
            field=models.ImageField(blank=True, upload_to='media/cheques/accNo'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='amount_img',
            field=models.ImageField(blank=True, upload_to='media/cheques/ammount'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='cheque_image',
            field=models.ImageField(blank=True, upload_to='media/cheques/'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='ifsc_img',
            field=models.ImageField(blank=True, upload_to='media/cheques/ifsc'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='micr_img',
            field=models.ImageField(blank=True, upload_to='media/cheques/micr'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='payee_img',
            field=models.ImageField(blank=True, upload_to='media/cheques/payee'),
        ),
        migrations.AlterField(
            model_name='chequedetail',
            name='signature',
            field=models.ImageField(blank=True, upload_to='media/cheques/signature'),
        ),
    ]
